version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=${MYSQLHOST}
      - DB_PORT=${MYSQLPORT}
      - DB_DATABASE=${MYSQLDATABASE}
      - DB_USERNAME=${MYSQLUSER}
      - DB_PASSWORD=${MYSQLPASSWORD}
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=${RAILWAY_STATIC_URL}/api
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: